apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test
  namespace: fluxcloud
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: test
    spec:
      containers:
      - name: test
        image: justinbarrick/fluxcloud:473acd3c677d5becd54eab55200430638c812d84b76ffb5f48b4eceb5afc53cee
        imagePullPolicy: Always
        ports:
        - containerPort: 3030
