---
# This defines a Kubernetes service for the Flux daemon, so you can
# access it with `fluxctl`. It defines a NodePort, meaning Kubernetes
# will assign a port to the service, on which it will be available on
# each node (host in the cluster). You can find the assigned port by
# doing something like
#
#
apiVersion: v1
kind: Service
metadata:
  name: flux
  namespace: fluxcloud
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3030
  selector:
    name: flux
