---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flux
  namespace: fluxcloud
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: flux
    spec:
      # The serviceAccount is only needed for Kubernetes with RBAC.
      # You will also need to create the resources in flux-account.yaml.
      serviceAccount: flux
      volumes:
      - name: git-key
        secret:
          secretName: flux-git-deploy
      containers:
      - name: flux
        # There are no ":latest" images for flux. Find the most recent
        # release or image version at https://quay.io/weaveworks/flux
        # and replace the tag here.
        image: quay.io/weaveworks/flux:1.2.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3030 # informational
        volumeMounts:
        - name: git-key
          mountPath: /etc/fluxd/ssh
        args:

        # if you deployed memcached in a different namespace to flux,
        # or with a different service name, you can supply these
        # following two arguments to tell fluxd how to connect to it.
        # - --memcached-hostname=memcached.default.svc.cluster.local
        # - --memcached-service=memcached

        - --git-url=git@github.com:justinbarrick/fluxcloud
        - --git-branch=master
        - --git-sync-tag=flux-sync-master
        - --git-path=manifests
        - --git-poll-interval=0m30s
        - --connect=ws://fluxcloud/

        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "500m"
