---
kind: Service
apiVersion: v1
metadata:
  name: fluxcloud
spec:
  selector:
    name: fluxcloud
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3030
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fluxcloud
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: fluxcloud
    spec:
      containers:
      - name: fluxcloud
        image: justinbarrick/fluxcloud:2018.5.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3030
        environment:
        - name: SLACK_URL
          value: https://hooks.slack.com/services/WEBHOOK_URL
        - name: SLACK_CHANNEL
          value: "#kubernetes"
        - name: SLACK_SERNAME
          value: Flux Deployer
        - name: SLACK_ICON_EMOJI
          value: :heart:
        - name: GITHUB_URL
          value: https://github.com/justinbarrick/fluxcloud/
