---
kind: Service
apiVersion: v1
metadata:
  name: fluxcloud
spec:
  selector:
    name: fluxcloud
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3031
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fluxcloud
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: fluxcloud
    spec:
      containers:
      - name: fluxcloud
        image: justinbarrick/fluxcloud:v0.2.9
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3031
        env:
        - name: SLACK_URL
          value: "https://hooks.slack.com/services/WEBHOOK_URL"
        - name: SLACK_CHANNEL
          value: "#kubernetes"
        - name: SLACK_USERNAME
          value: Flux Deployer
        - name: SLACK_ICON_EMOJI
          value: ":heart:"
        - name: GITHUB_URL
          value: "https://github.com/justinbarrick/fluxcloud/"
# Uncomment the lines below and update the ConfigMap to enable
# sending notifications to multiple Slack channels based upon
# the namespace from the created and/or updated resources.
#         - name: SLACK_CHANNEL_PATH
#           value: "/etc/config/channels.json"
#         volumeMounts:
#         - name: slack-config
#           mountPath: /etc/config/
#           readOnly: true
#       volumes:
#       - name: slack-config
#         configMap:
#           name: fluxcloud-channels
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: fluxcloud-slack
# data:
#   channels.json: |
#     [
#       {
#         "namespace": "*",
#         "channel": "#general"
#       },
#       {
#         "namespace": "team",
#         "channel": "#team"
#       }
#     ]
